name: Mongoose Shelly build
on:
  push:
jobs:
  build:
    name: Build for different Shelly models
    strategy:
      matrix:
        hwModel:    [ShellyPlugS]
        hwPlatform: [esp8266]
        targetFw:   [tasmota, haa, espurna]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      id: checkout_code
    - name: Build firmware
      uses: yaourdt/mongoose-os-action@v1.0.2
      with:
        mos-yml-path: .
        platform: ${{ matrix.hwPlatform }}
        build-var: MODEL=${{ matrix.hwModel }} --build-var TARGETFW=${{ matrix.targetFw }}
      id: mos_build
    - name: Upload Release Asset
      uses: actions/upload-artifact@v3
      with:
        path: ./build/fw.zip
        name: mg2${{ matrix.targetFw }}-${{ matrix.hwModel }}.zip
